# Generated by Django 3.1.1 on 2020-09-16 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_msg', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('timestamp',), 'verbose_name_plural': 'messages'},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='is_public',
            new_name='is_read',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='msg',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='message',
            name='conversation',
        ),
        migrations.AddField(
            model_name='message',
            name='last_update_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
    ]
