# Generated by Django 3.1.1 on 2020-09-17 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_msg', '0010_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name_plural': 'UserProfiles'},
        ),
    ]
