# Generated by Django 3.1.1 on 2020-09-17 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_msg', '0011_auto_20200917_0253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='password',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='username',
        ),
    ]
